name: animated_button
description: A new Flutter package with a customized Animated button.
version: 0.0.1
homepage: https://github.com/muhailyas/Flutter_Animated_button_package.git

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: